#cmakedefine HAVE_CALLOC 1 
#cmakedefine HAVE_DECL_FLOCKFILE 1
#cmakedefine HAVE_DECL_FTRYLOCKFILE 1
#cmakedefine HAVE_DECL_FUNLOCKFILE 1
#cmakedefine HAVE_DECL_GETRUSAGE 1
#cmakedefine HAVE_DECL_PTHREAD_ATTR_GETAFFINITY_NP 1
#cmakedefine HAVE_DECL_PTHREAD_ATTR_GETGUARDSIZE 1
#cmakedefine HAVE_DECL_PTHREAD_ATTR_GETSTACK 1
#cmakedefine HAVE_DECL_PTHREAD_ATTR_SETAFFINITY_NP 1
#cmakedefine HAVE_DECL_PTHREAD_ATTR_SETGUARDSIZE 1
#cmakedefine HAVE_DECL_PTHREAD_ATTR_SETSTACK 1
#cmakedefine HAVE_DECL_PTHREAD_GETAFFINITY_NP 1
#cmakedefine HAVE_DECL_PTHREAD_SETAFFINITY_NP 1
#cmakedefine HAVE_DECL_RCMD 1
#cmakedefine HAVE_DECL___ENV_LOCK 1
#cmakedefine HAVE_DECL___ENV_UNLOCK 1
#cmakedefine HAVE_ENVLOCK_H 1
#cmakedefine HAVE_EXECL 1
#cmakedefine HAVE_EXECLE 1
#cmakedefine HAVE_EXECLP 1
#cmakedefine HAVE_EXECV 1
#cmakedefine HAVE_EXECVE 1
#cmakedefine HAVE_EXECVP 1
#cmakedefine HAVE_FCNTL_R 1
#cmakedefine HAVE_FLOCKFILE 1
#cmakedefine HAVE_FSTAT_R 1
#cmakedefine HAVE_FTRYLOCKFILE 1
#cmakedefine HAVE_FUNLOCKFILE 1
#cmakedefine HAVE_GETCWD 1
#cmakedefine HAVE_GETCWD 1
#cmakedefine HAVE_GETTIMEOFDAY 1
#cmakedefine HAVE_INTTYPES_H 1
#cmakedefine HAVE_ISATTY 1
#cmakedefine HAVE_ISSETUGID 1
#cmakedefine HAVE_READDIR_R 1
#cmakedefine HAVE_SEMAPHORE_H 1
#cmakedefine HAVE_SIGHANDLER_T 1
#cmakedefine HAVE_STDLIB_H 1
#cmakedefine HAVE_STRINGS_H 1
#cmakedefine HAVE_STDINT 1
#cmakedefine HAVE_STRLCAT 1
#cmakedefine HAVE_STRLCPY 1
#cmakedefine HAVE_STRSEP 1
#cmakedefine HAVE_STRUCT__PTHREAD_CLEANUP_CONTEXT 1
#cmakedefine HAVE_TCGETPGRP 1
#cmakedefine HAVE_TTYNAME 1
#cmakedefine HAVE_UNISTD_H 1
#cmakedefine HAVE__CALLOC_R 1
#cmakedefine HAVE__CLOSE_R 1
#cmakedefine HAVE__FREE_R 1
#cmakedefine HAVE__GETPID_R 1
#cmakedefine HAVE__GETTIMEOFDAY_R 1
#cmakedefine HAVE__ISATTY_R 1
#cmakedefine HAVE__LSEEK_R 1
#cmakedefine HAVE__MALLOC_R 1
#cmakedefine HAVE__OPEN_R 1
#cmakedefine HAVE__READ_R 1
#cmakedefine HAVE__REALLOC_R 1
#cmakedefine HAVE__RENAME_R 1
#cmakedefine HAVE___ASSERT 1
#cmakedefine HAVE___ASSERT_FUNC 1
#cmakedefine RTEMS_NEWLIB 1
#cmakedefine SIZEOF_MODE_T @SIZEOF_MODE_T@
#cmakedefine SIZEOF_OFF_T @SIZEOF_OFF_T@
#cmakedefine SIZEOF_TIME_T @SIZEOF_TIME_T@
#cmakedefine SIZEOF_SIZE_T @SIZEOF_SIZE_T@
#cmakedefine __RTEMS_HAVE_SYS_CPUSET_H__ 1
#cmakedefine __RTEMS_HAVE_DECL_SIGALTSTACK__ 1
#cmakedefine __RTEMS_ADA__ 1
#cmakedefine __RTEMS_DO_NOT_INLINE_CORE_MUTEX_SEIZE__ 1
#cmakedefine __RTEMS_DO_NOT_INLINE_THREAD_ENABLE_DISPATCH__ 1
#cmakedefine __RTEMS_STRICT_ORDER_MUTEX__ 1

#cmakedefine RTEMS_DEBUG 1
#cmakedefine RTEMS_DRVMGR_STARTUP 1
#cmakedefine RTEMS_MULTIPROCESSING 1
#cmakedefine RTEMS_NETWORKING 1
#cmakedefine RTEMS_PARAVIRT 1
#cmakedefine RTEMS_POSIX_API 1
#cmakedefine RTEMS_PROFILING 1
#cmakedefine RTEMS_SMP

